- name: Install PHP
  hosts: webserver
  become: yes
  tasks:
    - name: Update yum cache
      ansible.builtin.yum:
        expire-cache: yes

    - name: Install PHP and required extensions
      ansible.builtin.yum:
        name:
          - php
          - php-cli
          - php-mysqlnd
          - php-gd
          - php-mbstring
          - php-xml
          - php-curl
          - php-process
          - php-common
        state: present

    - name: Create index.php
      ansible.builtin.copy:
        content: "<?php phpinfo(); ?>"
        dest: /var/www/html/index.php
        owner: apache
        group: apache
        mode: 0640

    - name: Update PHP-FPM config listen.mode
      lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: '^listen\.mode\s*=\s*.+'
        line: 'listen.mode = 0666'

    - name: Update PHP-FPM config listen.acl_users
      lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: '^listen\.acl_users\s*=\s*.+'
        line: ';listen.acl_users = apache,nginx'

    - name: Update PHP-FPM config listen.acl_users
      lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: '^listen\.acl_users\s*=\s*.+'
        line: ';listen.acl_users = apache,nginx'

    - name: Restart PHP-FPM
      systemd:
        name: php-fpm
        state: restarted

    - name: Restart Apache
      ansible.builtin.systemd:
        name: httpd
        state: restarted
