- hosts: isucon
  become: yes
  roles:
    - tools
  tags: tools

- hosts: isucon
  become: yes
  roles:
    - nginx
  tags: nginx

- hosts: isucon
  become: yes
  roles:
    - logrotate
  tags: logrotate