---
- name: install / update apt cache
  apt:
    update_cache: yes
  notify: debug apt update

- name: install / install apt package
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ apt_packages }}"

- name: install / install alp
  block:
    - name: install / download alp binary
      get_url:
        url: https://github.com/tkuchiki/alp/releases/download/v1.0.21/alp_linux_amd64.zip
        dest: /tmp/alp_linux_amd64.zip
        mode: '0755'

    - name: install / unzip alp binary
      unarchive:
        src: /tmp/alp_linux_amd64.zip
        dest: /usr/local/bin/
        remote_src: yes

    - name: install / make alp executable
      file:
        path: /usr/local/bin/alp
        mode: '0755'