- name: Update yum cache
  ansible.builtin.yum:
    expire-cache: yes

- name: Install Apache
  ansible.builtin.yum:
    name:
      - httpd
    state: present

- name: Install mod_ssl
  ansible.builtin.yum:
    name:
      - mod_ssl
    state: present

- name: Start Apache
  ansible.builtin.systemd:
    name: httpd
    state: started
